import { SelectedKost, LodgingCategoryType } from "../screens/customer/customerKosStore";

export interface TravelDestinationUI extends SelectedKost {
  categoryType: LodgingCategoryType;
  areaTag: string;
  badgeTag?: string;
  cashbackPoints?: number;
}

export const MOCK_HOTELS_AND_VILLAS: TravelDestinationUI[] = [
  {
    id: "htl-1",
    _id: "htl-1",
    categoryType: "hotel",
    name: "Santika Hotel & Convention Garut",
    type: "Hotel Bintang 4",
    address: "Jl. Cipanas Baru No.88, Panawuan, Tarogong Kaler, Garut",
    city: "Garut",
    areaTag: "Cipanas / Tarogong",
    badgeTag: "TERPOPULER",
    stars: 4,
    rating: 4.8,
    reviewCount: 342,
    price: 685000,
    cashbackPoints: 25000,
    description:
      "Hotel bintang 4 mewah dengan pemandangan Gunung Guntur langsung, kolam renang air panas alami, restoran khas Sunda, dan ruang konvensi modern.",
    facilities: ["Kolam Renang Air Panas", "Sarapan Gratis", "WiFi Cepat", "Restoran", "Fitness Center", "Parkir Luas"],
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80",
    ],
    hotelRooms: [
      {
        _id: "hr-1",
        roomName: "Superior Twin Bed (View Kolam)",
        bedType: "2 Single Bed",
        capacity: 2,
        pricePerNight: 685000,
        isAvailable: true,
        facilities: ["AC", "TV 43 inch", "Kulkas Mini", "Kamar Mandi Panas/Dingin", "Balkon"],
        images: ["https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80"],
        breakfastIncluded: true,
      },
      {
        _id: "hr-2",
        roomName: "Deluxe King Bed (View Gunung Guntur)",
        bedType: "1 King Bed",
        capacity: 2,
        pricePerNight: 850000,
        isAvailable: true,
        facilities: ["AC", "Bathtub Air Panas", "Smart TV", "Coffee Maker", "Balkon View Gunung"],
        images: ["https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80"],
        breakfastIncluded: true,
      },
      {
        _id: "hr-3",
        roomName: "Executive Family Suite",
        bedType: "2 Queen Bed",
        capacity: 4,
        pricePerNight: 1450000,
        isAvailable: true,
        facilities: ["Ruang Tamu Terpisah", "2 Kamar Mandi", "Bathtub Air Panas", "Balkon Panoramik"],
        images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80"],
        breakfastIncluded: true,
      },
    ],
    bankAccount: {
      paymentType: "bank",
      bankName: "BCA",
      accountNumber: "8472910394",
      accountHolder: "PT Santika Garut Utama",
    },
  },
  {
    id: "htl-2",
    _id: "htl-2",
    categoryType: "hotel",
    name: "Kamojang Green Hotel & Resort",
    type: "Resort & Bungalow",
    address: "Jl. Raya Kamojang KM.3, Samarang, Garut",
    city: "Garut",
    areaTag: "Kamojang / Samarang",
    badgeTag: "ECO RESORT",
    stars: 4,
    rating: 4.9,
    reviewCount: 428,
    price: 790000,
    cashbackPoints: 30000,
    description:
      "Resort alam berkonsep ramah lingkungan di atas danau buatan dengan udara sejuk pegunungan Kamojang. Cocok untuk liburan keluarga dan relaksasi.",
    facilities: ["Danau Dayung", "Kolam Air Panas Belerang", "Outbound & Camp", "Resto Terapung", "Spa Alami"],
    images: [
      "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80",
    ],
    hotelRooms: [
      {
        _id: "kgr-1",
        roomName: "Wooden Bungalow Lake View",
        bedType: "1 King Bed",
        capacity: 2,
        pricePerNight: 790000,
        isAvailable: true,
        facilities: ["Teras Danau", "Water Heater Alami", "Mini Bar", "Wifi"],
        images: ["https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80"],
        breakfastIncluded: true,
      },
      {
        _id: "kgr-2",
        roomName: "Villa 2 Kamar Pasundan Suite",
        bedType: "2 Queen Bed",
        capacity: 5,
        pricePerNight: 1650000,
        isAvailable: true,
        facilities: ["Kolam Rendam Pribadi", "Dapur Lengkap", "Teras Danau", "BBQ Area"],
        images: ["https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80"],
        breakfastIncluded: true,
      },
    ],
    bankAccount: {
      paymentType: "bank",
      bankName: "Mandiri",
      accountNumber: "1310088920192",
      accountHolder: "Kamojang Green Resort",
    },
  },
  {
    id: "htl-3",
    _id: "htl-3",
    categoryType: "hotel",
    name: "Rancabango Private Villa & Onsen",
    type: "Villa Private",
    address: "Jl. Rancabango No.12, Tarogong Kaler, Garut",
    city: "Garut",
    areaTag: "Cipanas / Tarogong",
    badgeTag: "PRIVATE ONSEN",
    stars: 5,
    rating: 4.9,
    reviewCount: 195,
    price: 1250000,
    cashbackPoints: 50000,
    description:
      "Villa eksklusif dengan private onsen (kolam air panas belerang pribadi) di dalam villa, pemandangan sawah dan Gunung Guntur yang asri.",
    facilities: ["Private Onsen", "Dapur Modern", "Smart Home", "Gazebo & Garden", "Free WiFi 100Mbps"],
    images: [
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
    ],
    hotelRooms: [
      {
        _id: "rv-1",
        roomName: "Villa Sakura 1 Bedroom + Onsen",
        bedType: "1 King Bed + 1 Sofa Bed",
        capacity: 3,
        pricePerNight: 1250000,
        isAvailable: true,
        facilities: ["Private Onsen", "Dapur", "Living Room", "Smart TV 55 inch"],
        images: ["https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80"],
        breakfastIncluded: true,
      },
    ],
  },
  {
    id: "htl-4",
    _id: "htl-4",
    categoryType: "hotel",
    name: "Dago Highland Resort & Heritage",
    type: "Hotel Bintang 3",
    address: "Jl. Bukit Pakar Timur IV No.88, Dago Atas, Bandung",
    city: "Bandung",
    areaTag: "Bandung Dago",
    badgeTag: "VIEW KOTA",
    stars: 3,
    rating: 4.7,
    reviewCount: 512,
    price: 495000,
    cashbackPoints: 18000,
    description:
      "Terletak di ketinggian Dago Atas Bandung dengan pemandangan gemerlap lampu kota di malam hari, udara sejuk dan suasana romantis.",
    facilities: ["Infinity Pool", "Sky Lounge Cafe", "Free Shuttle ke Dago Plaza", "Meeting Room"],
    images: [
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80",
    ],
    hotelRooms: [
      {
        _id: "dh-1",
        roomName: "Deluxe Mountain View",
        bedType: "1 Queen Bed",
        capacity: 2,
        pricePerNight: 495000,
        isAvailable: true,
        facilities: ["AC", "Balkon View Kota", "Water Heater", "Tea/Coffee Maker"],
        images: ["https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80"],
        breakfastIncluded: true,
      },
    ],
  },
];

export const MOCK_TOURIST_ATTRACTIONS: TravelDestinationUI[] = [
  {
    id: "wst-1",
    _id: "wst-1",
    categoryType: "wisata",
    name: "Taman Air Sabda Alam Cipanas",
    type: "Waterpark & Rekreasi Air Panas",
    address: "Jl. Raya Cipanas No.3, Rancabango, Tarogong Kaler, Garut",
    city: "Garut",
    areaTag: "Cipanas / Tarogong",
    badgeTag: "INSTANT PASS ⚡",
    rating: 4.8,
    reviewCount: 890,
    price: 45000,
    cashbackPoints: 5000,
    openHours: "07:00 - 18:00 WIB (Buka Setiap Hari)",
    description:
      "Wahana taman air panas alami terlengkap di Garut dengan kolam ombak, seluncuran spiral raksasa, ember tumpah, dan terapi air belerang yang menyehatkan.",
    facilities: ["Kolam Ombak", "Waterboom Spiral", "Kolam Terapi Ikan", "Foodcourt & Gazebo", "Loker & Ruang Ganti", "Musholla"],
    images: [
      "https://images.unsplash.com/photo-1582650625119-3a31f8418b7d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&w=800&q=80",
    ],
    wisataTickets: [
      {
        _id: "tkt-1",
        ticketName: "Tiket Masuk Reguler (Weekday)",
        ticketType: "reguler",
        price: 45000,
        description: "Akses ke seluruh kolam air panas, kolam anak, dan kolam renang olympic.",
        includedFacilities: ["Kolam Air Panas Alami", "Kolam Anak", "Ruang Bilas Standar"],
      },
      {
        _id: "tkt-2",
        ticketName: "Tiket Terusan Wahana Lengkap (All-Access)",
        ticketType: "terusan",
        price: 75000,
        description: "Akses bebas ke kolam ombak tsunami, waterboom spiral, kolam terapi ikan, dan flying fox.",
        includedFacilities: ["Kolam Ombak Tsunami", "Waterboom Raksasa", "Terapi Ikan Garra Rufa", "Gazebo Free 1 Jam"],
      },
      {
        _id: "tkt-3",
        ticketName: "Paket Keluarga (4 Orang) + Gazebo",
        ticketType: "vip",
        price: 240000,
        description: "Tiket untuk 4 orang dewasa/anak + sewa gazebo seharian penuh + voucher makan Rp 50.000.",
        includedFacilities: ["Tiket 4 Orang", "Gazebo Seharian", "Voucher Makan Rp 50k"],
      },
    ],
    bankAccount: {
      paymentType: "bank",
      bankName: "BCA",
      accountNumber: "0248819201",
      accountHolder: "PT Sabda Alam Garut",
    },
  },
  {
    id: "wst-2",
    _id: "wst-2",
    categoryType: "wisata",
    name: "Kawah Kamojang Geothermal & Hutan Pinus",
    type: "Wisata Alam & Geothermal",
    address: "Kawasan Konservasi Kamojang, Samarang - Ibun, Garut",
    city: "Garut",
    areaTag: "Kamojang / Samarang",
    badgeTag: "ALAM & EDUKASI",
    rating: 4.9,
    reviewCount: 650,
    price: 20000,
    cashbackPoints: 3000,
    openHours: "07:30 - 17:00 WIB",
    description:
      "Cagar alam dan pembangkit geothermal tertua di Indonesia dengan fenomena Kawah Kereta Api beruap alami, danau uap belerang, serta hutan pinus asri.",
    facilities: ["Kawah Kereta Api", "Danau Ciharus Trekking", "Spot Foto Pinus", "Saung Kopi Geothermal", "Toilet & Musholla"],
    images: [
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80",
    ],
    wisataTickets: [
      {
        _id: "tkt-kj-1",
        ticketName: "Tiket Masuk Kawasan Kawah Kamojang",
        ticketType: "reguler",
        price: 20000,
        description: "Tiket masuk resmi perorangan ke kawasan kawah uap dan jembatan kayu hutan pinus.",
        includedFacilities: ["Akses Kawah Kereta", "Akses Jembatan Kayu", "Asuransi Wisatawan"],
      },
      {
        _id: "tkt-kj-2",
        ticketName: "Tiket Bundling Guide Lokal & Sauna Uap Alami",
        ticketType: "vip",
        price: 60000,
        description: "Didampingi pemandu lokal berlisensi + sesi sauna uap geothermal di Kawah Manuk.",
        includedFacilities: ["Pemandu Lokal Ramah", "Sauna Uap Alami 30 Menit", "Air Mineral"],
      },
    ],
  },
  {
    id: "wst-3",
    _id: "wst-3",
    categoryType: "wisata",
    name: "Wisata Danau Situ Bagendit 2.0",
    type: "Danau & Rekreasi Keluarga",
    address: "Jl. KH. Hasan Arif, Sukamukti, Banyuresmi, Garut",
    city: "Garut",
    areaTag: "Garut Kota",
    badgeTag: "REVITALISASI BARU",
    rating: 4.7,
    reviewCount: 1120,
    price: 15000,
    cashbackPoints: 2000,
    openHours: "08:00 - 17:30 WIB",
    description:
      "Danau legendaris yang telah direvitalisasi berstandar internasional dengan dermaga apung ikonik, perahu naga, jembatan kayu estetik, dan spot kuliner.",
    facilities: ["Dermaga Apung Ikonik", "Perahu Bebek & Rakit Cinta", "Taman Bunga Tepi Danau", "Plaza Kuliner Sunda"],
    images: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=800&q=80",
    ],
    wisataTickets: [
      {
        _id: "tkt-bg-1",
        ticketName: "Tiket Masuk Kawasan Situ Bagendit",
        ticketType: "reguler",
        price: 15000,
        description: "Akses masuk gerbang utama, dermaga apung, dan taman tepi danau.",
        includedFacilities: ["Akses Dermaga Apung", "Taman Bermain", "Asuransi"],
      },
      {
        _id: "tkt-bg-2",
        ticketName: "Tiket Terusan + Wahana Perahu Rakit",
        ticketType: "terusan",
        price: 35000,
        description: "Tiket masuk kawasan + keliling danau dengan perahu rakit bambu 45 menit.",
        includedFacilities: ["Tiket Masuk", "Keliling Perahu Rakit", "Pelampung Keselamatan"],
      },
    ],
  },
  {
    id: "wst-4",
    _id: "wst-4",
    categoryType: "wisata",
    name: "Taman Wisata Alam Gunung Papandayan",
    type: "Wisata Alam & Camping Ground",
    address: "Desa Sirnajaya, Cisurupan, Garut",
    city: "Garut",
    areaTag: "Garut Kota",
    badgeTag: "TREKKING & CAMP",
    rating: 4.9,
    reviewCount: 1420,
    price: 35000,
    cashbackPoints: 6000,
    openHours: "24 Jam (Untuk Camping) • 07:00 - 17:00 WIB (Kunjungan Harian)",
    description:
      "Gunung berapi ramah pendaki pemula dengan pemandangan Hutan Mati yang mistis eksotis, padang bunga Edelweiss Tegal Alun, dan kolam terapi air panas.",
    facilities: ["Kawah Aktif Papandayan", "Hutan Mati Ikonik", "Tegal Alun Edelweiss", "Pondok Saladah Camping", "Kolam Rendam Belerang"],
    images: [
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    ],
    wisataTickets: [
      {
        _id: "tkt-ppd-1",
        ticketName: "Tiket Masuk Wisatawan Nusantara (Harian)",
        ticketType: "reguler",
        price: 35000,
        description: "Tiket kunjungan harian ke area kawah dan Hutan Mati.",
        includedFacilities: ["Akses Jalur Kawah", "Akses Hutan Mati", "Asuransi TWA"],
      },
      {
        _id: "tkt-ppd-2",
        ticketName: "Tiket Camping 2D1N di Pondok Saladah",
        ticketType: "terusan",
        price: 65000,
        description: "Izin berkemah di camping ground Pondok Saladah + akses kolam air panas.",
        includedFacilities: ["Izin Camp 2 Hari 1 Malam", "Akses Kolam Rendam", "Asuransi Rimba"],
      },
    ],
  },
];
